### PR TITLE
Update and expand on documentation

### PR DESCRIPTION
**Pull request by MichaelSearson**
## What has changed
The documentation has been improved to be more detailed, with the intent of making web-view easier to work with for newcomers to the Rust ecosystem. This includes a step-by-step sample, as well as a section for known issues with the current version.

## Future improvements

I'd like to continue working on the documentation to include some rudimentary benchmarks against similar libraries such as Electron, React Native, and Flutter to highlight the niche web-view offers. I'd also like to refactor the example projects - but I feel they're out of scope for this commit!

---

Any issues with the formating or content let me know!

### CODE REVIEW

**Comment by erlend-sh** [comment]
@zxey Seems very safe to merge considering it's just a `README.md` edit 🙂

**Comment by zxey** [comment]
Yeah, sorry it took so long for me to look at this. @MichaelSearson Could you please put the [original](https://camo.githubusercontent.com/91f0d77090b4e9446ae60ba43921549818c7a3da/68747470733a2f2f692e696d6775722e636f6d2f5a3363327a77442e706e67) image below this summary:
> This library provides Rust bindings for the webview library to allow easy creation of cross-platform Rust desktop apps with GUIs based on web technologies.

I like that it's something that catches people attention.

**Comment by MichaelSearson** [comment]
@zxey No worries! Agreed RE: the image placement. Good shout!

**Comment by zxey** [comment]
Thanks!

**Pull request merged**
