### PR TITLE
Problem: No Elm example

### PR DESCRIPTION
**Pull request by julianpistorius**
Solution: Add simple Elm 'counter' example

Elm counter example copied from https://github.com/evancz/guide.elm-lang.org

### CODE REVIEW

**Comment by Boscop** [comment]
For the todo-ps example, this line inlines the assets into the index.html and saves it as bundle.html:

https://github.com/Boscop/web-view/blob/35db78e04fc4d6633b704a962c418e5d39b5b449/examples/todo-ps/package.json#L10

Everytime someone depends on the web-view crate, cargo downloads the whole crate so I added this exclude line to exclude the large bundle.html:
https://github.com/Boscop/web-view/blob/685129abf05f66a442072fe09b54f48a224cd118/Cargo.toml#L11

It would be good if you could add your index.html, too. (You can check with `cargo package` if it's properly excluded from the package).

**Comment by julianpistorius** [comment]
Righto! I'll have a crack at that.

**Comment by julianpistorius** [comment]
How does that look?

**Comment by Boscop** [comment]
Thanks!

**Pull request merged**
