### PR TITLE
Fix for memory leak in ffi_dispatch_handler and ffi_invoke_handler

### PR DESCRIPTION
**Pull request by gin66**
Hi,

few days ago I have extended the time example into an own small application. I kept it running on my server. Today I was surprised about memory pressure messages in the console window, from where the app has been started. With htop have seen, that the small application occupied ~98GB. So I searched in the unsafe code regions for memory leaks. I assume, that I have found two. Please check my patches. I will keep my app running again for some time and hope the problem is solved.

### CODE REVIEW

**Comment by zxey** [comment]
Thank you for submitting this patch. I have only one small nitpick, could you call mem::forget directly instead of introducing new method?

**Comment by gin66** [comment]
Updated accordingly

**Comment by gin66** [comment]
Just reread the documentation. mem::forget does not free the memory. So the leak is not closed.
Need to rework the patch again.

**Comment by gin66** [comment]
The 98G in htop is shown already at start up. So the memory pressure warning seems to be a better indicator. Have updated the code (see patch) and keep the app running with 10ms timer.

**Comment by gin66** [comment]
No memory pressure warnings after more than 12 hours and much more timer activity. Recommend to integrate the patch or revise the code to close the memory leak.

**Comment by gin66** [comment]
The „Merge branch ‚master‘ into master“ message in course of this pull request is weird. Looks like a github issue, because the referred commit has nothing to do with this pull request.

**Comment by zxey** [comment]
It is fine, I just resolved the issue via GitHub ui and merged it.
Also thanks that you tested this and created a fix.

**Pull request merged**
