### PR TITLE
Implement maximize method, for frameless windows, for edge and gtk backend.

### PR DESCRIPTION
**Pull request by Blakeinstein**
I am unsure of how to achieve this on cocoa.

This should allow one to call webview.set_maximized(bool) to maximize the window.

### CODE REVIEW

**Comment by zxey** [comment]
Thanks for your contribution, I will definitely merge this, we just need to add it for macOS backend. If you cannot figure this out, I will look into it eventually. Same for #200.

**Comment by Blakeinstein** [comment]
I have plans to look into it! I just plan on finishing up one last thing before I fix cross-platform.

I would also love to keep a separate fork that allows for perfect frame handling on a frame-less window. So that users can implement their own title bars.

Since I plan on overriding nchittest on winapi, i might need to keep it separate until i figure out how to modify it with the constructor.

I dont own a mac, so cocoa is newgrounds for me, but I am sure its possible.

**Comment by Blakeinstein** [comment]
@zxey One small problem, for macos, The concept of maximize doesnt exist, as such, an alternative is to use the zoom feature, [performZoom](https://developer.apple.com/documentation/appkit/nswindow/1419450-performzoom) or [zoom](https://developer.apple.com/documentation/appkit/nswindow/1419513-zoom) though due to a lack of a test place, I cant confirm.

**Comment by zxey** [comment]
Yes, it seems you cannot maximize windows on macOS, only zoom them, I think that is sufficient for feature parity across platforms.

**Comment by Blakeinstein** [comment]
I am looking into setting up a vm for macos through my friends macbook pro, once that is done I will look into miniaturize and zoom.

**Comment by Blakeinstein** [comment]
Implemented maximize for cocoa and mshtml, only thing I havent tested is gtk, but I am quite sure it should work

**Comment by zxey** [comment]
Thank you for going through with this and implementing it for all platforms, contributors such as yourself are a joy to work with.

**Comment by Blakeinstein** [comment]
Thanks! Could you perhaps also look into #200 ? As per documentation it should work but, apparently doesnt.

**Pull request merged**
