### PR TITLE
yew todo example

### PR DESCRIPTION
**Pull request by Extrawurst**

### CODE REVIEW

**Comment by zxey** [comment]
Hi, thanks for this contribution, yew example is long overdue so I am glad that someone got to it!

If you could do few things so the example is self contained, that would be perfect:
- include the todomvc rust source code directly into todo-yew directory
  - copy over `yew/examples/todomvc` to `web-view/examples/todo-yew/todomvc`
  - edit `todomvc/Cargo.toml` so it points to specific yew version instead of `yew = { path = "../.." }`
- include `base.css` and `index.css` into todo-yew directory and edit `todomvc/static/index.html` accordingly so the resources get pulled through actix offline and not cdn online
- provide build instructions, so users can easily know how to edit and replace the included example files
  - something along the lines: `cd into todomvc`, `cargo build`, `cp artifacts to example dir`, `cd back to root` and `cargo run --example todo-yew`

**Comment by Extrawurst** [comment]
That sounds a lot like what I did in a separate repo where I wanted to switch out Actix to hyper (which got the binary down by **2mb**) -> https://github.com/Extrawurst/rust-webview-todomvc-yew

but yeah I will do that with the Actix based example in the PR here too

**Comment by zxey** [comment]
Damn, that hyper example seems much simpler than the actix based one, if you want you can also send me a PR of the same example as the actix one here, but with actix switched with hyper.

Also feel free to add your repo in this PR to showcase down in README.md, if you'd like!

**Comment by Extrawurst** [comment]
Ok I made those changes but left it to use Actix to keep closer to the other example, linked my example repo with a hyper based version.

**Comment by zxey** [comment]
Perfect, thank you.

**Comment by Extrawurst** [comment]
@zxey thank you and thanks for building this awesome library!

**Pull request merged**
