### PR TITLE
Move examples/ to new crate

### PR DESCRIPTION
**Pull request by zec**
This proposed change, made in response to issue #257, moves the example programs from the `web-view` crate into a new crate, named `webview-examples`.

Some parts of this PR as it stands (e.g., whether this is a **desirable** solution to #257, the exact name of the new crate) could be up for debate. Constructive feedback, if any, is welcomed.

### CODE REVIEW

**Comment by zxey** [comment]
I like this change, could you add some basic README.md to webview-example directory?
Just so users know how exactly run the examples, can be just few lines, something along:

> To run any of these examples just type:
> ```
> cargo run --example <name-of-example>
> ```
> where \<name-of-example\> is a name of file from examples/ directory without .rs extension.

**Comment by zec** [comment]
Done.

**Comment by zxey** [comment]
Thank you!

**Comment by zec** [comment]
You're welcome.

**Pull request merged**
